version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=taxi
    volumes:
      - taxi_pg_data:/bitnami/postgresql
  
  server:
    build: ./server
    container_name: server_c
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
  web:
    build: ./web
    container_name: web_c
    ports:
      - '80:80'
    stdin_open: true
    tty: true

volumes:
  taxi_pg_data: